### ISSUE TITLE
Some issue about FixGroupService.java 

### ISSUE THREAD

**Issue by Librazy** [xmusoftware15/ModuleStandardGroup-Public#4]
https://github.com/xmusoftware15/ModuleStandardGroup-Public/commit/289f3946a29b4d4e00d13ecbf18727d132148504#r26413150
https://github.com/xmusoftware15/ModuleStandardGroup-Public/commit/289f3946a29b4d4e00d13ecbf18727d132148504#r26413214

**Comment by xmusoftware15** [comment]
We will modify two errors as soon as possible
